blog/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "/articles", to:"articles#index"
  #get "/articles/:id", to:"articles#show"

  resources :articles

end

blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
    primary_abstract_class
end

blog/app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: {message: "is mandatory"}
    validates :body, presence: true, length: { minimum: 10 }
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/views/articles/_form.html.erb
<section class = "d-flex justify-content-center border-4 border border-primary w-25">
<%= form_with model: article do |form| %>
  <div class="p-3 mb-2 bg-white text-black">
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class = "p-3 mb-2 bg-white text-black">
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="p-3 mb-2 bg-white text-black">
    <%= form.submit %>
  </div>
<% end %>
</section>

blog/app/views/articles/edit.html.erb
<h1 class = "p-3 mb-2 bg-white text-black font-family-verdana"> Edit Article </h1>
<%= render "form", article: @article %>

blog/app/views/articles/index.html.erb
<section class = "border-4 border border-primary">
    <h1 class = "p-3 mb-2 bg-white text-black d-flex justify-content-center">Articles#index</h1>
    <p class = "p-3 mb-2 bg-white text-black d-flex justify-content-center">Find me in app/views/articles/index.html.erb</p>

    <h2 class = "p-3 mb-2 bg-white text-black d-flex justify-content-center">Ruby Project</h2>
    <ul>
        <% @articles.each do |article| %>
        <li class = "p-3 mb-2 bg-white text-black d-flex justify-content-center">
            <a href="/articles/<%= article.id %>"><%= article.title%></a>
        </li>
        <% end %>
    </ul>
</section>

blog/app/views/articles/new.html.erb
<h1 class = "p-3 mb-2 bg-white text-black">New Article</h1>

<%= render "form", article: @article %>

blog/app/views/articles/show.html.erb
<section class = "border-4 border border-primary">
  <h1 class = "p-3 mb-2 bg-white text-black d-flex justify-content-center"><%= @article.title %></h1>

  <p class = "p-3 mb-2 bg-white text-black d-flex justify-content-center"><%= @article.body %></p>

  <ul>
    <li class = "p-3 mb-2 bg-white text-black d-flex justify-content-center"><%= link_to "Edit", edit_article_path(@article) %></li>
    <li class = "p-3 mb-2 bg-white text-black d-flex justify-content-center"><%= link_to "Destroy", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
    } %></li>
  </ul>
</section>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>